### ISSUE TITLE
Editing the paper

### ISSUE THREAD

**Issue by ketch** [ketch/positiveRK#17]
- [x] Rephrase comment on time step for example II (David)
- [x] Remove material on dense output
- [x] Remove early part of section 4.2 and instead discuss that we are interested in behavior for relatively large dt
- [x] Consistently use the notation established in the early sections
- [x] Fix typos
- [x] Trim section 4.3 to include only the theorem and final lemma
- [x] Edit beginning of section 5.1 -- (5.1-2) should appear much earlier and be referenced here.
- [x] Make pseudocode more precise and clear
- [x] Move necessary and sufficient conditions (Section 6.1) to beginning of paper.  Also discuss that under this condition, LP is always feasible for first order methods.
- [x] Rename subsections in section 6
- [x] Use same y-axis for Figures 6c and 6d

**Comment by ranocha** [comment]
- [x] Fix sign in front of `0.003 u_4` in eq. (6.6d) (should be minus)

**Comment by ketch** [comment]
@snuesslein I edited the beginning of Section 5.1 but there is an "X" there that I need you to fill in with a number.

**Comment by snuesslein** [comment]
I do not have this number right now, but i will add the functionality to obtain it

**Comment by ranocha** [comment]
I think your last PR #21 closed this issue, didn't it, @ketch?

**Comment by ketch** [comment]
No, we're waiting for that number from @snuesslein .

**Comment by ranocha** [comment]
I thought that number was added in c10a0333b6a9938cebfd9dfa2d83bb1dc5b6656b: 
https://github.com/ketch/positiveRK/blob/c10a0333b6a9938cebfd9dfa2d83bb1dc5b6656b/nusslein_vsrp/latex/overview.tex#L863

**Comment by ketch** [comment]
Looks like it was.  I hadn't seen that.
