### ISSUE TITLE
Figure 3 (change of stability region)

### ISSUE THREAD

**Issue by ranocha** [ketch/positiveRK#2]
I'm a bit confused by Figure 3. How shall I interpret the diagonal lines there?
Could we also add some axes labels?

**Comment by snuesslein** [comment]
This was simply meant as hatching of the inside of the stability region.

**Comment by ranocha** [comment]
Ah, okay. Could you please add such an explanation to the text? When your commit message is something like `***; closes #2`, this will close this issue when you push your changes.
