### ISSUE TITLE
Undefined/ambiguous terminology regarding implicit Euler extrapolation

### ISSUE THREAD

**Issue by ketch** [ketch/positiveRK#23]
The implicit Euler extrapolation methods need to be clearly defined either through a citation or giving the details in the paper (this could go in an appendix).  Also, terms like "chain of BE" probably should be made more precise.  Finally, it seems strange to write both "BE" and "Im-Euler" to mean the same thing.  I think "EX3" and Im-Euler 3" also refer to the same thing.

**Comment by ranocha** [comment]
Most parts should now use the same notation. The following parts have to be adapted to the unified notation of the BE 3 extrapolation method:
- [x] Legend of Figure 7
- [x] Legend of Figure 10 (maybe just remove EX3 there?)
