### ISSUE TITLE
add a README.md

### ISSUE THREAD

**Issue by ranocha** [ketch/positiveRK#6]
And add a description/title at the top (I think only @ketch can do that since I don't have the rights). A good description would be the tentative title `Positivity-Preserving Adaptive Runge–Kutta Methods`, I think.

**Comment by ketch** [comment]
Good idea.  However, there is a lot of stuff in this repository and not all of it is Stephan's project.  I think it would be best to move everything related to this specific project to a subdirectory and put a Readme there (with an additional top-level readme explaining the different things that are here).

**Comment by ranocha** [comment]
That sounds good for me. Could you please do that (since you have the best overview)?

**Comment by ketch** [comment]
This is done.
